apiVersion: v1
kind: Namespace
metadata:
  name: application-canary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: application-canary
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: avattar/fp-app:{TAG}
        name: wa3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
          requests:
            memory: "150Mi"
            cpu: "10m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: application-canary
spec:
  type: ClusterIP
  ports:
  - port: 9095
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: application-canary
  name: app-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "<WEIGHT>"
spec:
  rules:
  - host: app.fp
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 9095