apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: application
spec:
  type: ClusterIP
  ports:
  - port: 9095
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
