apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: application
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9091
  selector:
    app: app
  type: ClusterIP
